spring:
  datasource:
    url: jdbc:mysql://ip:port/changgou_seckill?useUnicode=true&characterSet=utf-8&charset=utf-8
    username: user
    password: name
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: ip
    port:
    password: password
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl